CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE topics
  ADD COLUMN user_id INT UNSIGNED NULL AFTER id,
  ADD CONSTRAINT fk_topics_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE study_logs
  ADD COLUMN user_id INT UNSIGNED NULL AFTER id,
  ADD CONSTRAINT fk_study_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE checkpoints
  ADD COLUMN user_id INT UNSIGNED NULL AFTER id,
  ADD COLUMN study_log_id INT UNSIGNED NULL AFTER topic_id,
  ADD CONSTRAINT fk_checkpoints_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_checkpoints_study_log FOREIGN KEY (study_log_id) REFERENCES study_logs(id) ON DELETE SET NULL;

ALTER TABLE mistakes
  ADD COLUMN user_id INT UNSIGNED NULL AFTER id,
  ADD CONSTRAINT fk_mistakes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
